"""
Migration Report Generator

Generates HTML reports from migration results and AD inventory analysis.
Uses Jinja2 templates for formatting.
"""

import json
import sys
from datetime import datetime
from pathlib import Path

from jinja2 import Template

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AD Migration Report - {{ report_title }}</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 32px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
        h1 { color: #1a237e; border-bottom: 3px solid #1a237e; padding-bottom: 8px; }
        h2 { color: #283593; margin-top: 32px; }
        .summary-cards { display: flex; gap: 16px; flex-wrap: wrap; margin: 16px 0; }
        .card { background: #e8eaf6; padding: 16px; border-radius: 8px; min-width: 180px; }
        .card .number { font-size: 32px; font-weight: bold; color: #1a237e; }
        .card .label { color: #5c6bc0; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { background: #1a237e; color: white; padding: 10px; text-align: left; }
        td { padding: 8px 10px; border-bottom: 1px solid #e0e0e0; }
        tr:nth-child(even) { background: #f5f5f5; }
        .status-pass { color: #2e7d32; font-weight: bold; }
        .status-fail { color: #c62828; font-weight: bold; }
        .status-warn { color: #ef6c00; font-weight: bold; }
        .status-skip { color: #757575; }
        .recommendation { background: #fff3e0; border-left: 4px solid #ff9800; padding: 12px; margin: 8px 0; border-radius: 0 4px 4px 0; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e0e0e0; color: #9e9e9e; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ report_title }}</h1>
        <p>Generated: {{ generated_at }}</p>

        {% if summary %}
        <h2>Summary</h2>
        <div class="summary-cards">
            <div class="card">
                <div class="number">{{ summary.user_stats.total }}</div>
                <div class="label">Total Users</div>
            </div>
            <div class="card">
                <div class="number">{{ summary.user_stats.enabled }}</div>
                <div class="label">Enabled</div>
            </div>
            <div class="card">
                <div class="number">{{ summary.user_stats.disabled }}</div>
                <div class="label">Disabled</div>
            </div>
            <div class="card">
                <div class="number">{{ summary.user_stats.stale_90_days }}</div>
                <div class="label">Stale (90d)</div>
            </div>
            <div class="card">
                <div class="number">{{ summary.group_stats.total_groups }}</div>
                <div class="label">Total Groups</div>
            </div>
        </div>

        {% if summary.recommendations %}
        <h2>Recommendations</h2>
        {% for rec in summary.recommendations %}
        <div class="recommendation">{{ rec }}</div>
        {% endfor %}
        {% endif %}

        {% if summary.ou_distribution %}
        <h2>OU Distribution</h2>
        <table>
            <tr><th>Organizational Unit</th><th>User Count</th></tr>
            {% for ou, count in summary.ou_distribution.items() %}
            <tr><td>{{ ou }}</td><td>{{ count }}</td></tr>
            {% endfor %}
        </table>
        {% endif %}
        {% endif %}

        {% if migration_results %}
        <h2>Migration Results</h2>
        <div class="summary-cards">
            <div class="card">
                <div class="number">{{ migration_results.succeeded }}</div>
                <div class="label">Succeeded</div>
            </div>
            <div class="card">
                <div class="number">{{ migration_results.failed }}</div>
                <div class="label">Failed</div>
            </div>
            <div class="card">
                <div class="number">{{ migration_results.skipped }}</div>
                <div class="label">Skipped</div>
            </div>
        </div>

        {% if migration_results.log %}
        <h2>Detailed Log</h2>
        <table>
            <tr><th>Object</th><th>Type</th><th>Status</th><th>Error</th></tr>
            {% for entry in migration_results.log %}
            <tr>
                <td>{{ entry.object_name }}</td>
                <td>{{ entry.object_type }}</td>
                <td class="status-{{ entry.status | lower }}">{{ entry.status }}</td>
                <td>{{ entry.error_message or '' }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        {% endif %}

        <div class="footer">
            Generated by Windows AD Migration Tool
        </div>
    </div>
</body>
</html>
"""


def generate_pre_migration_report(summary_file: str, output_file: str):
    """Generate an HTML pre-migration analysis report."""
    with open(summary_file, "r") as f:
        summary = json.load(f)

    template = Template(REPORT_TEMPLATE)
    html = template.render(
        report_title="Pre-Migration Analysis Report",
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        summary=summary,
        migration_results=None,
    )

    Path(output_file).write_text(html, encoding="utf-8")
    print(f"Report generated: {output_file}")


def generate_post_migration_report(results_file: str, output_file: str):
    """Generate an HTML post-migration results report."""
    with open(results_file, "r") as f:
        results = json.load(f)

    template = Template(REPORT_TEMPLATE)
    html = template.render(
        report_title="Post-Migration Results Report",
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        summary=None,
        migration_results=results,
    )

    Path(output_file).write_text(html, encoding="utf-8")
    print(f"Report generated: {output_file}")


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage:")
        print("  Pre-migration:  python report_generator.py pre <summary.json> <output.html>")
        print("  Post-migration: python report_generator.py post <results.json> <output.html>")
        sys.exit(1)

    report_type = sys.argv[1]
    input_file = sys.argv[2]
    output_file = sys.argv[3]

    if report_type == "pre":
        generate_pre_migration_report(input_file, output_file)
    elif report_type == "post":
        generate_post_migration_report(input_file, output_file)
    else:
        print(f"Unknown report type: {report_type}")
        sys.exit(1)
