"use client";

import { useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase/browser";

type TotpEnroll = {
  id: string;
  // Supabase returns an object with QR + secret for TOTP
  totp?: { qr_code?: string; secret?: string };
};

export default function SecurityClient() {
  const supabase = supabaseBrowser();

  const [loading, setLoading] = useState(true);
  const [totpFactorId, setTotpFactorId] = useState<string | null>(null);

  // Enrollment state
  const [enrolling, setEnrolling] = useState(false);
  const [enrollData, setEnrollData] = useState<TotpEnroll | null>(null);
  const [code, setCode] = useState("");
  const [msg, setMsg] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);

  async function refreshFactors() {
    setLoading(true);
    setErr(null);
    const res = await supabase.auth.mfa.listFactors();

    const existingTotp = res.data?.totp?.[0];
    setTotpFactorId(existingTotp?.id ?? null);

    setLoading(false);
  }

  useEffect(() => {
    refreshFactors();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const qrSvg = useMemo(() => {
    // Supabase typically returns an SVG string for qr_code.
    // We’ll render it as HTML. (It’s generated by Supabase, not user input.)
    return enrollData?.totp?.qr_code ?? null;
  }, [enrollData]);

  async function startEnroll() {
    setMsg(null);
    setErr(null);
    setEnrolling(true);
    setEnrollData(null);
    setCode("");

    const { data, error } = await supabase.auth.mfa.enroll({ factorType: "totp" });

    if (error) {
      setErr(error.message);
      setEnrolling(false);
      return;
    }

    setEnrollData(data as TotpEnroll);
    setEnrolling(false);
  }

  async function verifyAndEnable(e: React.FormEvent) {
    e.preventDefault();
    setMsg(null);
    setErr(null);

    if (!enrollData?.id) {
      setErr("No enrollment in progress.");
      return;
    }
    if (code.replace(/\D/g, "").length !== 6) {
      setErr("Enter a valid 6-digit code.");
      return;
    }

    const { error } = await supabase.auth.mfa.challengeAndVerify({
      factorId: enrollData.id,
      code: code.replace(/\D/g, ""),
    });

    if (error) {
      setErr(error.message);
      return;
    }

    setMsg("Authenticator app enabled.");
    setEnrollData(null);
    setCode("");
    await refreshFactors();
  }

  async function removeTotp() {
    setMsg(null);
    setErr(null);

    if (!totpFactorId) return;

    const { error } = await supabase.auth.mfa.unenroll({ factorId: totpFactorId });

    if (error) {
      setErr(error.message);
      return;
    }

    setMsg("Authenticator app removed.");
    await refreshFactors();
  }

  if (loading) return <div style={{ padding: 24 }}>Loading factors…</div>;

  return (
    <div style={{ marginTop: 24 }}>
      {msg && <p style={{ color: "green" }}>{msg}</p>}
      {err && <p style={{ color: "crimson" }}>{err}</p>}

      <div style={{ padding: 16, border: "1px solid #ddd", borderRadius: 12 }}>
        <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700 }}>Authenticator app (TOTP)</h2>
        <p style={{ marginTop: 6, opacity: 0.75 }}>
          Recommended if you use freemail. Adds a second step at login.
        </p>

        {totpFactorId ? (
          <div>
            <p style={{ marginTop: 10 }}>
              Status: <strong>Enabled</strong>
            </p>
            <button onClick={removeTotp} style={{ padding: 10 }}>
              Remove authenticator
            </button>
          </div>
        ) : (
          <div>
            <p style={{ marginTop: 10 }}>
              Status: <strong>Not enabled</strong>
            </p>
            <button onClick={startEnroll} disabled={enrolling} style={{ padding: 10 }}>
              {enrolling ? "Starting…" : "Set up authenticator"}
            </button>
          </div>
        )}
      </div>

      {enrollData && (
        <div style={{ marginTop: 16, padding: 16, border: "1px solid #ddd", borderRadius: 12 }}>
          <h3 style={{ margin: 0, fontSize: 16, fontWeight: 700 }}>Step 1: Scan QR</h3>
          <p style={{ opacity: 0.75 }}>
            Scan with Google Authenticator / Authy / 1Password.
          </p>

          {qrSvg ? (
            <div
              style={{ background: "#fff", padding: 12, display: "inline-block", borderRadius: 12 }}
              dangerouslySetInnerHTML={{ __html: qrSvg }}
            />
          ) : (
            <p style={{ color: "crimson" }}>
              QR code not available. (We can fall back to secret key if needed.)
            </p>
          )}

          {enrollData.totp?.secret && (
            <p style={{ marginTop: 10, fontSize: 12, opacity: 0.8 }}>
              Secret (backup): <code>{enrollData.totp.secret}</code>
            </p>
          )}

          <hr style={{ margin: "16px 0" }} />

          <h3 style={{ margin: 0, fontSize: 16, fontWeight: 700 }}>Step 2: Enter code</h3>
          <form onSubmit={verifyAndEnable} style={{ marginTop: 10 }}>
            <input
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
              inputMode="numeric"
              placeholder="123456"
              style={{ padding: 10, fontSize: 18, letterSpacing: 4, width: 160 }}
              required
            />
            <button type="submit" style={{ padding: 10, marginLeft: 10 }}>
              Verify & Enable
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
